import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "./(Home)/Navbar";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Footer from "./(Home)/Footer";
import { Bounce, ToastContainer } from "react-toastify";
import TopBar from "./(Home)/Topbar";
import TawkTo from "@/lib/TawkTo";
import { getHomeData } from "@/lib/services";

const inter = Outfit({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Online Exam Relief",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
    nocache: true,
    googleBot: {
      index: false,
      follow: false,
      noimageindex: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = await getHomeData();

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TopBar />

          <Navbar />
          <ToastContainer
            className="z-[999999]"
            position="top-right"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={false}
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
            transition={Bounce}
          />
          {children}
          <Footer />
          <TawkTo tawkToScript={content.data.tawkToScript} />
        </ThemeProvider>
      </body>
    </html>
  );
}
